name: deploy

on: 
  push:
    branches:
      - master

jobs:
  deploy:
    name: '部署'
    runs-on: ubuntu-latest
    steps:
    - name: 
      run: |
        npm run docs:build
        cd docs/.vuepress/dist
        git init
        git add -A
        git commit -m 'deploy'
        git push -f git@github.com:24code/blog.git master:gh-pages
